# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20151229_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='SOFTWARE', max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
