# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_quicksend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksend',
            name='reason',
            field=models.CharField(blank=True, choices=[('SOFTWARE', 'software'), ('WEBSITE', 'website'), ('ECOMM', 'e-commerce'), ('CONSULT', 'consulting'), ('BI', 'B.I.')], default='SOFTWARE', max_length=24),
        ),
    ]
