# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20160817_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('project', models.TextField()),
            ],
        ),
    ]
